# Configuração GLOBAL (default)
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# Configuração de PRODUÇÃO (PostgreSQL)
spring:
  config:
    activate:
      on-profile: ${PROFILES_APP}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
# Configuração de DESENVOLVIMENTO (H2 - apenas para testes locais)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop